server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: products
        uri: http://localhost:8010
        predicates:
        - Path=/api/v1/products/**
      - id: transaction
        uri: http://localhost:8020/
        predicates:
        - Path=/api/v1/transactions/**
